apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: wechat-server-interaction
  name: wechat-server-interaction
  namespace: gridvo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: wechat-server-interaction
    spec:
      containers:
      - name: wechat-server-interaction
        image: 10.0.3.31:5000/gridvo/wechat-server-interaction:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: ZOOKEEPER_SERVICE_HOST
          value: "zookeeper"
        - name: ZOOKEEPER_SERVICE_PORT
          value: "2181"
        - name: ZK_TRACER_HTTP
          value: "true"
        - name: IS_DEBUG
          value: "true"
        - name: SG_WECHAT_PORTAL_DOMAIN
          value: "pascal.gridvo.com"
