apiVersion: v1
kind: Service
metadata:
  labels:
    name: wechat-server-interaction
  name: wechat-server-interaction
  namespace: gridvo
spec:
  selector: 
    name: wechat-server-interaction
  type: NodePort
  ports:
     - port: 80
       targetPort: 3001
       nodePort: 31015
