apiVersion: v1
kind: Service
metadata:
  name: wechat-server-interaction
spec:
  selector: 
    app: wechat-server-interaction
  type: NodePort
  ports:
     - port: 80
       targetPort: 3001
       nodePort: 8001
