apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wechat-server-interaction
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wechat-server-interaction
    spec:
      containers:
      - name: wechat-server-interaction
        image: 10.0.2.62:5000/gridvo/wechat-server-interaction:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: ZK_TRACER_HTTP
          value: "true"             
        - name: SG_WECHAT_PORTAL_DOMAIN
          value: "pascal.gridvo.com"