version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  wechat-server-interaction:
    build: .
    image: gridvo/wechat-server-interaction:dev
    container_name: wechat-server-interaction
    depends_on:
     - zookeeper
     - kafka
    environment:
      ZOOKEEPER_SERVICE_HOST: zookeeper
      ZOOKEEPER_SERVICE_PORT: 2181
  unittest:
    image: node:latest
    container_name: unittest
    volumes_from:
     - wechat-server-interaction
    depends_on:
     - zookeeper
     - kafka
     - wechat-server-interaction
    environment:
      ZOOKEEPER_SERVICE_HOST: zookeeper
      ZOOKEEPER_SERVICE_PORT: 2181
    working_dir: /home/wechat-server-interaction
    command: npm test