version: '2'
services:
  kafka-zookeeper:
    image: openzipkin/zipkin-kafka:1.18.0
    container_name: kafka-zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
    ports:
      - "127.0.0.1:2181:2181"
      - "127.0.0.1:9092:9092"
  storage:
    image: openzipkin/zipkin-cassandra:1.18.0
    container_name: cassandra
    ports:
      - 9042:9042
  zipkin:
    image: openzipkin/zipkin:1.18.0
    container_name: zipkin
    environment:
      - STORAGE_TYPE=cassandra
      - CASSANDRA_CONTACT_POINTS=cassandra
    ports:
      - 9410:9410
      - 9411:9411
    depends_on:
      - storage
  dependencies:
    image: openzipkin/zipkin-dependencies
    container_name: dependencies
    entrypoint: crond -f
    environment:
      - STORAGE_TYPE=cassandra
      - CASSANDRA_CONTACT_POINTS=cassandra
    depends_on:
      - storage