version: '2'
services:
  kafka-zookeeper:
    image: openzipkin/zipkin-kafka:1.18.0
    container_name: kafka-zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
    ports:
      - "127.0.0.1:2181:2181"
      - "127.0.0.1:9092:9092"